# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - frontendailiftprod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # GitHub token
          github_token: ${{github.token}}
          # Repository name with owner
          repo: ar-ya/build
          # Artifact name (download all artifacts in not specified)
          name: node-app
          # Download latest artifact
          latest: true
          # Artifact unpack location
          path:  ./
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app2
          path: .
      

